server:
  port: 8081
spring:
  application:
    name: shopperX
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/shopperX
    username: postgres
    password: root
  jpa:
    hibbernate:
      ddl-auto: update
  security:
    user:
      name: admin
      password: admin




